services:
  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_HOST}
    env_file:
      - .env

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  alembic-revision:
    build: .
    command: sh -c "alembic revision --autogenerate -m \"Initial migration\""
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - DATABASE_URL=${DATABASE_URL}

  alembic-upgrade:
    build: .
    command: alembic upgrade head
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - DATABASE_URL=${DATABASE_URL}

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

      
volumes:
  postgres_data:
